export const HEADERS_LONG: string[] = [
  'Numéro d\'article (9)',
  'Libellé article (35)',
  'Mot directeur (10)',
  'Libellé réduit (35)',
  'Libellé réduit 2 (20)',
  'Type de produit',
  'Capacité',
  'Statut article',
  'Code EAN (20)',
  'Libellé étiquette (35)',
  'Code référence',
  'Famille AA',
  'Sous-famille AB',
  'Sous-sous-famille AC',
  'Segment AD',
  'Réserve AE',
  'Réserve AF',
  'Réserve AG',
  'Réserve AH',
  'Statut ARKABASE',
  'Unité conditionnement sortie (UCOSVA)',
  'Conversion vente (CVENVA)',
  'Poids brut unité (PBUEVA)',
  'Type TVA (TYPXVA)',
  'Degré (DEGRAR)',
  'Unité article (UTARUT)',
  'Unité de vente (UTVLUT)',
  'Date activation (DACTEF)',
  'Statut fiche (STAFEF)',
  'N° article conditionnement (NARCVA)',
  'Hauteur (HAUEVA)',
  'Largeur (LAUEVA)',
  'Longueur (LOUEVA)',
  'Masse volumique (MVENVA)',
  'Sous conditionnement (SSUCVA)',
  'Sélection (SEALAR)',
  'Niveau logistique (NVLOVC)',
  'Libellé niveau logistique (LVLOVC)',
  'Type VL (TYVLVC)',
  'Niveau livraison (NVLIVC)',
  'Nb sous-pack (NBSPVC)',
  'Nb pack (NBPCVC)',
  'Nb couches (NCOUVC)',
  'Nb unités/colis (NBUEVC)',
  'Poids brut (PBUEVC)',
  'Poids net (PNETVC)',
  'Hauteur VL (HAUEVC)',
  'Largeur VL (LAUEVC)',
  'Longueur VL (LOUEVC)',
  'Article conditionnement (NARCVC)',
  'Statut conditionnement (CSTAVC)',
  'Niveau palette (NVLOVP)',
  'Niveau livraison palette (NVLIVP)',
  'Nb sous-pack palette (NBSPVP)',
  'Nb pack palette (NBPCVP)',
  'Nb couches palette (NCOUVP)',
  'Nb unités/palette (NBUEVP)',
  'Poids brut palette (PBUEVP)',
  'Poids net palette (PNETVP)',
  'Hauteur palette (HAUEVP)',
  'Largeur palette (LAUEVP)',
  'Longueur palette (LOUEVP)',
  'Article palette (NARCVP)',
  'Agence (AGCEAR)',
  'SKU (ARSKAR)',
  'Durée stock (DSTXAR)',
  'Délai préparation (DLPEAR)',
  'Température min (TMINAR)',
  'Température max (TMAXAR)',
  'Entrepôt K1 (NENTK1)',
  'Date appli K1 (DAPLK1)',
  'Règle K1 (REASK1)',
  'Type règle K1 (TYREK1)',
  'Entrepôt 1 (NEN1KA)',
  'Niveau lot (NVLOEF)',
  'Unité stock (USTCEF)',
  'Quota net (QCDNEF)',
  'Quota taxé (QCDXEF)',
  'Incrément (INCREF)',
  'Type règle enc (TYREEF)',
  'Origine appro (ORAPEF)',
  'Entrepôt V1 (NENTV1)',
  'Niveau livraison V1 (NVLOV1)',
  'Quota net V1 (QCDNV1)',
  'Quota taxé V1 (QCDXV1)',
  'Incrément V1 (INCRV1)',
  'Type étiquette (TYETAR)',
  'Nb étiquettes (NBETAR)',
  'Libellé étiquette alt (LETIAL)',
  'Libellé réduit étiquette (LREDAL)',
  'Classe article (CLANAL)',
  'Poids colis (POCLVQ)',
  'Poids tare (PTARVQ)',
  'Groupe barème (GRBAVQ)',
  'Type barème (TYBAVQ)',
  'Libellé 1 (LIB1LE)',
  'Libellé 2 (LIB2LE)',
  'Libellé 3 (LIB3LE)',
  'Libellé 4 (LIB4LE)',
  'Libellé 5 (LIB5LE)',
  'N° article annexe (NARXAX)',
  'Adresse AR (ARDRAX)',
  'Libellé article fiche (LARFEF)'
];

export const HEADERS_CODES: string[] = [
  'NARTAR',
  'LARTAR',
  'MDIRAR',
  'LAREAR',
  'LREDAR',
  'TYPRAR',
  'CAPRAR',
  'CSTAAR',
  'CEANAR',
  'LETIAR',
  'TREFAR',
  'AA',
  'AB',
  'AC',
  'AD',
  'AE',
  'AF',
  'AG',
  'AH',
  'STATAR',
  'UCOSVA',
  'CVENVA',
  'PBUEVA',
  'TYPXVA',
  'DEGRAR',
  'UTARUT',
  'UTVLUT',
  'DACTEF',
  'STAFEF',
  'NARCVA',
  'HAUEVA',
  'LAUEVA',
  'LOUEVA',
  'MVENVA',
  'SSUCVA',
  'SEALAR',
  'NVLOVC',
  'LVLOVC',
  'TYVLVC',
  'NVLIVC',
  'NBSPVC',
  'NBPCVC',
  'NCOUVC',
  'NBUEVC',
  'PBUEVC',
  'PNETVC',
  'HAUEVC',
  'LAUEVC',
  'LOUEVC',
  'NARCVC',
  'CSTAVC',
  'NVLOVP',
  'NVLIVP',
  'NBSPVP',
  'NBPCVP',
  'NCOUVP',
  'NBUEVP',
  'PBUEVP',
  'PNETVP',
  'HAUEVP',
  'LAUEVP',
  'LOUEVP',
  'NARCVP',
  'AGCEAR',
  'ARSKAR',
  'DSTXAR',
  'DLPEAR',
  'TMINAR',
  'TMAXAR',
  'NENTK1',
  'DAPLK1',
  'REASK1',
  'TYREK1',
  'NEN1KA',
  'NVLOEF',
  'USTCEF',
  'QCDNEF',
  'QCDXEF',
  'INCREF',
  'TYREEF',
  'ORAPEF',
  'NENTV1',
  'NVLOV1',
  'QCDNV1',
  'QCDXV1',
  'INCRV1',
  'TYETAR',
  'NBETAR',
  'LETIAL',
  'LREDAL',
  'CLANAL',
  'POCLVQ',
  'PTARVQ',
  'GRBAVQ',
  'TYBAVQ',
  'LIB1LE',
  'LIB2LE',
  'LIB3LE',
  'LIB4LE',
  'LIB5LE',
  'NARXAX',
  'ARDRAX',
  'LARFEF',
  'NORAEF',
  'GENECB'
];

const REF_MAP: Record<string, string | number> = {
  PNETVA: 0.1,
  CENTVA: 0.0,
  NARCVA: 0,
  TYREK1: 1,
  TYREEF: '01',
  ORAPEF: 'C',
  TYETAR: '01',
  NBETAR: 1,
};

export const REF_ROW: (string | number)[] = HEADERS_CODES.map(code => (REF_MAP as any)[code] ?? '');

export const MAX_LENGTHS: Record<string, number> = {
  B: 35,
  C: 10,
  D: 35,
  E: 20,
  J: 35,
  AW: 35,
  I: 20,
};
